"""Backup safety and native archive handling, without operational connections."""
from contextlib import redirect_stderr, redirect_stdout
import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import MagicMock, Mock, patch

from scripts import backup_storage as backup
from roly.storage_config import ConnectionConfig


TARGET = "rolymoly_qa_" + "a" * 32
SOURCE = "rolymoly"
NATIVE_SQL = """-- PostgreSQL native archive
\\restrict ABC123
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SELECT pg_catalog.set_config('search_path', '', false);
CREATE SCHEMA rolymoly;
CREATE TABLE rolymoly.members (
    id bigint NOT NULL,
    notes text DEFAULT ''::text NOT NULL
);
ALTER TABLE rolymoly.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rolymoly.members_id_seq
    START WITH 1
    INCREMENT BY 1
);
COPY rolymoly.members (id, notes) FROM stdin;
1\tmy rolymoly.members text; DROP SCHEMA rolymoly CASCADE;
2\t한글 \\t escaped \\n data
\\.
SELECT pg_catalog.setval('rolymoly.members_id_seq', 2, true);
ALTER TABLE ONLY rolymoly.members ADD CONSTRAINT members_pkey PRIMARY KEY (id);
CREATE INDEX member_notes ON rolymoly.members USING btree (notes);
-- PostgreSQL database dump complete
\\unrestrict ABC123
"""


class BackupStorageTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="roly-backup-tests-")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        for change in (patch.object(backup, "ROOT", self.root), patch.object(backup, "BACKUP_ROOT", self.root / ".data" / "backups")):
            change.start()
            self.addCleanup(change.stop)
        self.config = ConnectionConfig("example.pooler.supabase.com", "postgres.synthetic", "private-test-password")
        self.native = {"pg_dump": "pg_dump", "pg_restore": "pg_restore", "pg_dump_major": 17, "pg_restore_major": 17}
        self.fingerprint = {"schema_version": 6, "tables": {"members": {"rows": 2, "sha256": "synthetic"}}}

    def archive(self):
        directory = backup.BACKUP_ROOT / "synthetic-backup"
        directory.mkdir(parents=True)
        data = b"PGDMPsynthetic-native-archive"
        (directory / "application.dump").write_bytes(data)
        manifest = {"format": 1, "scope": "complete_private_app_schema", "schema": "rolymoly", "pg_dump_major": 17,
                    "archive_sha256": hashlib.sha256(data).hexdigest(), "fingerprint": self.fingerprint}
        (directory / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
        return directory

    def connection(self):
        connection = MagicMock()

        def execute(statement, params=None):
            result = MagicMock()
            if "EXISTS" in str(statement):
                result.fetchone.return_value = (False,)
            elif "relkind='S'" in str(statement):
                result.__iter__.return_value = iter([("members_id_seq",)])
            elif "last_value" in str(statement):
                result.fetchone.return_value = (2, True)
            elif str(statement) == "SHOW server_version_num":
                result.fetchone.return_value = ("170006",)
            elif "pg_export_snapshot" in str(statement):
                result.fetchone.return_value = ("00000003-0000001B-1",)
            return result

        connection.execute.side_effect = execute
        return connection

    def test_missing_native_tools_stops_before_config_or_connection(self):
        with patch.object(backup.shutil, "which", return_value=None), patch.object(backup, "load_config") as config, redirect_stdout(io.StringIO()) as output:
            self.assertEqual(backup.main(["create"]), 2)
        self.assertIn("pg_dump", output.getvalue())
        config.assert_not_called()
        self.assertFalse(backup.BACKUP_ROOT.exists())

    def test_tool_version_mismatch_rejected(self):
        with patch.object(backup.shutil, "which", side_effect=lambda name: name), patch.object(backup.subprocess, "run", side_effect=[
            SimpleNamespace(returncode=0, stdout=b"pg_dump (PostgreSQL) 17.6"),
            SimpleNamespace(returncode=0, stdout=b"pg_restore (PostgreSQL) 16.9"),
        ]):
            with self.assertRaisesRegex(backup.BackupError, "must match"):
                backup.tools_available()

    def test_tool_check_does_not_connect_or_read_secrets(self):
        with patch.object(backup, "tools_available", return_value=self.native), patch.object(backup, "load_config") as config, redirect_stdout(io.StringIO()) as output:
            self.assertEqual(backup.main(["check-tools"]), 0)
        config.assert_not_called()
        self.assertFalse(json.loads(output.getvalue())["database_connected"])

    def test_native_credentials_are_environment_only_and_pg_overrides_removed(self):
        with patch.dict(os.environ, {"PGSERVICE": "untrusted", "PGSSLMODE": "disable"}):
            env = backup._native_environment(self.config)
        self.assertNotIn("PGSERVICE", env)
        self.assertEqual(env["PGPASSWORD"], self.config.password)
        self.assertEqual(env["PGSSLMODE"], "require")
        self.assertIn("default_transaction_read_only=on", env["PGOPTIONS"])

    def test_native_tool_raw_error_is_sanitized(self):
        with patch.object(backup.subprocess, "run", return_value=SimpleNamespace(returncode=1, stdout=b"", stderr=b"private-password")):
            with self.assertRaises(backup.BackupError) as error:
                backup._native(["pg_dump"])
        self.assertNotIn("private-password", str(error.exception))

    def test_native_timeout_is_sanitized_at_cli(self):
        with patch.object(backup, "tools_available", side_effect=subprocess.TimeoutExpired("private-password", 1)), redirect_stdout(io.StringIO()) as output:
            self.assertEqual(backup.main(["check-tools"]), 1)
        self.assertNotIn("private-password", output.getvalue())

    def test_private_path_rejects_project_source_and_root(self):
        for path in (self.root / "static" / "backup", self.root / ".." / "private", backup.BACKUP_ROOT):
            with self.subTest(path=path), self.assertRaises(backup.BackupError):
                backup._private_path(path)

    def test_backup_uses_shared_readonly_snapshot_and_complete_native_schema(self):
        connection = self.connection()

        def write_dump(command, **kwargs):
            self.assertIn("--format=custom", command)
            self.assertIn("--snapshot=00000003-0000001B-1", command)
            self.assertIn("--schema=rolymoly", command)
            self.assertNotIn(self.config.password, " ".join(command))
            Path(next(item[7:] for item in command if item.startswith("--file="))).write_bytes(b"PGDMPnative-full-data")
            return b""

        with patch.object(backup, "_native", side_effect=write_dump), patch.object(backup, "inspect_schema", return_value=self.fingerprint):
            result = backup.create_backup(self.config, self.native, connect=Mock(return_value=connection))
        self.assertTrue(result["ok"])
        self.assertFalse(result["restore_verified"])
        commands = [str(call.args[0]) for call in connection.execute.call_args_list]
        self.assertIn("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY", commands)
        self.assertIn("ROLLBACK", commands)
        self.assertNotIn("COMMIT", commands)
        path = self.root / result["backup_directory"]
        manifest = json.loads((path / "manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["fingerprint"], self.fingerprint)
        self.assertNotIn(self.config.password, (path / "manifest.json").read_text())
        connection.close.assert_called_once()

    def test_failed_dump_cleans_only_its_new_directory(self):
        sentinel = backup.BACKUP_ROOT / "previous"
        sentinel.mkdir(parents=True)
        (sentinel / "keep.dump").write_bytes(b"keep")
        connection = self.connection()
        with patch.object(backup, "_native", side_effect=backup.BackupError("Failed")), patch.object(backup, "inspect_schema", return_value=self.fingerprint):
            with self.assertRaises(backup.BackupError):
                backup.create_backup(self.config, self.native, connect=Mock(return_value=connection))
        self.assertEqual(list(backup.BACKUP_ROOT.iterdir()), [sentinel])
        connection.close.assert_called_once()

    def test_older_native_dump_rejected_before_export(self):
        connection = self.connection()
        with patch.object(backup, "_native") as native:
            with self.assertRaisesRegex(backup.BackupError, "older"):
                backup.create_backup(self.config, dict(self.native, pg_dump_major=16), connect=Mock(return_value=connection))
        native.assert_not_called()
        self.assertFalse(list(backup.BACKUP_ROOT.iterdir()))

    def test_copy_member_text_and_korean_are_never_remapped(self):
        operations = list(backup._dump_operations(NATIVE_SQL))
        copies = [(statement, payload) for statement, payload in operations if payload is not None]
        self.assertEqual(len(copies), 1)
        statement, payload = copies[0]
        mapped = backup.remap_operation(statement, SOURCE, TARGET)
        self.assertIn(TARGET + ".members", mapped)
        self.assertIn("my rolymoly.members text; DROP SCHEMA rolymoly CASCADE;", payload)
        self.assertIn("한글", payload)
        self.assertNotIn(TARGET, payload)
        self.assertEqual(len(operations), 10)

    def test_native_multiline_identity_constraint_and_index_remapping(self):
        for statement, payload in backup._dump_operations(NATIVE_SQL):
            mapped = backup.remap_operation(statement, SOURCE, TARGET)
            if mapped and not mapped.startswith("SET ") and "set_config" not in mapped:
                self.assertNotIn("rolymoly.", mapped)

    def test_incomplete_copy_and_sql_rejected(self):
        for content in ("COPY rolymoly.members (id) FROM stdin;\n1\n", "CREATE TABLE rolymoly.members (id bigint", "SELECT 'unclosed\n"):
            with self.subTest(content=content), self.assertRaises(backup.BackupError):
                list(backup._dump_operations(content))

    def test_multiline_quoted_literal_is_not_split_at_semicolon(self):
        content = "CREATE TABLE rolymoly.members (notes text DEFAULT 'hello;\nworld');\n"
        parts = list(backup._dump_operations(content))
        self.assertEqual(len(parts), 1)
        self.assertIn("'hello;\nworld'", backup.remap_operation(parts[0][0], SOURCE, TARGET))

    def test_quoted_schema_and_column_identifiers_are_supported(self):
        value = 'COPY "rolymoly"."competition_games" (id, "position") FROM stdin'
        self.assertEqual(backup.remap_operation(value, SOURCE, TARGET), value.replace('"rolymoly"', '"' + TARGET + '"'))
        with self.assertRaises(backup.BackupError):
            backup.remap_operation('ALTER TABLE rolymoly.members ADD FOREIGN KEY (id) REFERENCES "public"."accounts"(id)', SOURCE, TARGET)

    def test_only_regclass_literals_change_and_member_default_text_stays(self):
        original = "CREATE TABLE rolymoly.members (notes text DEFAULT 'rolymoly.members', id bigint DEFAULT nextval('rolymoly.members_id_seq'::regclass))"
        result = backup.remap_operation(original, SOURCE, TARGET)
        self.assertIn("DEFAULT 'rolymoly.members'", result)
        self.assertIn("nextval('" + TARGET + ".members_id_seq'::regclass)", result)

    def test_operating_or_malformed_target_rejected(self):
        for target in ("rolymoly", "public", "rolymoly_qa_abc", SOURCE + ";DROP SCHEMA public"):
            with self.subTest(target=target), self.assertRaises(backup.BackupError):
                backup.remap_operation("CREATE SCHEMA rolymoly", SOURCE, target)

    def test_unsupported_and_cross_schema_mutations_fail_closed(self):
        for statement in (
            "DROP SCHEMA rolymoly CASCADE", "CREATE TABLE public.members (id bigint)",
            "ALTER TABLE rolymoly.members ADD FOREIGN KEY (id) REFERENCES public.accounts(id)",
            "CREATE FUNCTION rolymoly.bad() RETURNS void LANGUAGE sql AS $$SELECT 1$$",
            "COPY rolymoly.members FROM PROGRAM 'bad'", "SET search_path = rolymoly",
            "SELECT pg_catalog.setval('public.members_id_seq', 1, true)",
            "ALTER TABLE rolymoly.members SET SCHEMA public",
            "CREATE TABLE rolymoly.members (id bigint DEFAULT nextval('public.seq'::regclass))",
        ):
            with self.subTest(statement=statement), self.assertRaises(backup.BackupError):
                backup.remap_operation(statement, SOURCE, TARGET)

    def test_restore_never_accepts_destination_schema(self):
        with self.assertRaises(SystemExit), redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            backup.main(["verify", "--target-schema", "rolymoly"])

    def test_corrupt_archive_stops_before_any_database_connection(self):
        directory = self.archive()
        (directory / "application.dump").write_bytes(b"tampered")
        connect = Mock()
        with self.assertRaisesRegex(backup.BackupError, "checksum"):
            backup.verify_backup(self.config, self.native, directory, connect=connect)
        connect.assert_not_called()

    def test_unknown_native_statement_stops_before_database_connection(self):
        directory, connect = self.archive(), Mock()
        with patch.object(backup, "_native", return_value=b"DROP SCHEMA rolymoly CASCADE;\n"):
            with self.assertRaises(backup.BackupError):
                backup.verify_backup(self.config, self.native, directory, connect=connect)
        connect.assert_not_called()

    def test_restore_hashes_sequences_then_rolls_back_new_qa_schema(self):
        directory, connection = self.archive(), self.connection()
        connect = Mock(return_value=connection)
        with patch.object(backup, "_native", return_value=NATIVE_SQL.encode("utf-8")), patch.object(backup, "inspect_schema", return_value=self.fingerprint):
            result = backup.verify_backup(self.config, self.native, directory, connect=connect)
        self.assertTrue(result["row_and_structure_hashes_match"])
        self.assertTrue(result["qa_schema_removed"])
        self.assertEqual(result["sequences"], 1)
        commands = [str(call.args[0]) for call in connection.execute.call_args_list]
        self.assertIn("ROLLBACK", commands)
        self.assertNotIn("COMMIT", commands)
        self.assertFalse(any("DROP SCHEMA" in cmd for cmd in commands))
        self.assertFalse(any("rolymoly.members" in cmd for cmd in commands))
        self.assertEqual(sum("CREATE SCHEMA" in cmd for cmd in commands), 1)
        connection.close.assert_called_once()

    def test_mismatched_table_hash_rolls_back_and_reports_failure(self):
        directory, connection = self.archive(), self.connection()
        with patch.object(backup, "_native", return_value=NATIVE_SQL.encode("utf-8")), patch.object(backup, "inspect_schema", return_value={}):
            with self.assertRaisesRegex(backup.BackupError, "fingerprints"):
                backup.verify_backup(self.config, self.native, directory, connect=Mock(return_value=connection))
        self.assertIn("ROLLBACK", [call.args[0] for call in connection.execute.call_args_list])
        connection.close.assert_called_once()

    def test_restore_driver_error_is_not_printed_by_cli(self):
        with patch.object(backup, "tools_available", return_value=self.native), patch.object(backup, "load_config", return_value=self.config), patch.object(backup, "verify_backup", side_effect=RuntimeError(self.config.password)), redirect_stdout(io.StringIO()) as output:
            self.assertEqual(backup.main(["verify", "--backup-dir", str(backup.BACKUP_ROOT / "test")]), 1)
        self.assertNotIn(self.config.password, output.getvalue())


if __name__ == "__main__":
    unittest.main()
